"""
generate_strategy_universe_json.py
===================================
Generates 08_docs/strategy_universe_exhaustive.json from hardcoded entries.
Run once to regenerate; safe to re-run (overwrites previous file).

Usage:
    python generate_strategy_universe_json.py
"""
import json
from pathlib import Path

ENTRIES = [
    # ── Family A: OFI ─────────────────────────────────────────────────────────
    {
        "key": "ofi_continuation",
        "family": "A_OFI",
        "name": "OFI Continuation",
        "priority": 1,
        "status": "survivor",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10"],
        "hypothesis": "Strong positive OFI (top percentile) above VWAP → institutions accumulating → price follows",
        "entry_logic": "ofi_5 > rolling_quantile(ofi_5, 90-95th pct); close > session_vwap; de-clustered (no re-entry within 5 bars)",
        "exit_logic": "ATR-based stop (1×ATR) and target (1.5-2×ATR × RR); timeout at hold_bars",
        "risk_model": "ATR stop, RR ratio, 1-contract exclusivity",
        "features_required": ["ofi_5", "session_vwap", "atr"],
        "lookahead_risks": ["rolling quantile must use past bars only; min_periods enforced"],
        "failure_modes": ["rare signal if threshold too high", "VWAP drifts intraday making filter inconsistent"],
        "param_grid": {"ofi_pct": [90, 93, 95], "roll_win": [60, 120], "rr_ratio": [1.5, 2.0], "hold_bars": [5, 10]},
        "notes": "Core survivor — GC and SI both pass evidence gate at 1-tick slippage.",
    },
    {
        "key": "ofi_reversal",
        "family": "A_OFI",
        "name": "OFI Reversal (Exhaustion)",
        "priority": 1,
        "status": "tested",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10"],
        "hypothesis": "Extreme OFI with no price follow-through (small body) = exhausted aggression → fade",
        "entry_logic": "ofi_5 >= rolling_quantile(90-95th); body_frac < 0.2-0.35 (small candle body relative to range)",
        "exit_logic": "ATR stop and target; timeout",
        "risk_model": "ATR stop, RR, exclusivity",
        "features_required": ["ofi_5", "atr", "open", "high", "low", "close"],
        "lookahead_risks": ["quantile window must be past-only"],
        "failure_modes": ["body fraction filter inconsistent across symbols with different tick sizes"],
        "param_grid": {"ofi_pct": [85, 90, 95], "body_fraction": [0.2, 0.35], "rr_ratio": [1.5, 2.0], "hold_bars": [5, 10]},
        "notes": "Reversal logic — complement to OFI Continuation; lower win rate, higher R per trade.",
    },
    {
        "key": "ofi_microprice",
        "family": "A_OFI",
        "name": "OFI + Microprice Divergence",
        "priority": 1,
        "status": "tested",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10"],
        "hypothesis": "Microprice above last close (book tilted bullish) + positive OFI momentum = convergence trade",
        "entry_logic": "mp_diff > rolling_quantile(mp_pct); ofi_5 > rolling_quantile(ofi_pct); combined signal",
        "exit_logic": "ATR stop and target; timeout",
        "risk_model": "ATR stop, RR, exclusivity",
        "features_required": ["microprice_last", "ofi_5", "atr"],
        "lookahead_risks": ["both quantiles must be past-only"],
        "failure_modes": ["low trade count when both filters are strict"],
        "param_grid": {"mp_diff_pct": [60, 70, 80], "ofi_pct": [60, 70], "rr_ratio": [1.5, 2.0], "hold_bars": [5, 10]},
        "notes": "Dual-filter convergence; more selective than plain OFI.",
    },
    {
        "key": "ofi_multi_level_confirmation",
        "family": "A_OFI",
        "name": "Multi-Level OFI Confirmation",
        "priority": 1,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10"],
        "hypothesis": "L1+L3+L5 OFI all aligned in same direction → higher conviction, less noise",
        "entry_logic": "ofi_1, ofi_3, ofi_5 all above/below respective rolling percentiles simultaneously",
        "exit_logic": "ATR stop and target",
        "risk_model": "ATR stop, RR, exclusivity",
        "features_required": ["ofi_1", "ofi_3", "ofi_5"],
        "lookahead_risks": ["each OFI column computed from past bars only"],
        "failure_modes": ["signals too rare if all three must align; low trade count"],
        "param_grid": {"ofi_pct": [70, 80], "rr_ratio": [1.5, 2.0], "hold_bars": [5, 10]},
        "notes": "Priority 1 — test with L2 data already available.",
    },
    {
        "key": "ofi_with_spread_filter",
        "family": "A_OFI",
        "name": "OFI with Spread Filter",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10"],
        "hypothesis": "OFI signals are more reliable when spread is tight (normal market conditions)",
        "entry_logic": "OFI threshold exceeded AND spread_mean < percentile(spread, 50th)",
        "exit_logic": "ATR stop and target",
        "risk_model": "ATR stop, RR, exclusivity",
        "features_required": ["ofi_5", "spread_mean"],
        "lookahead_risks": ["spread percentile computed on rolling window"],
        "failure_modes": ["spread filter eliminates too many signals in normal GC/SI tick structure"],
        "param_grid": {"ofi_pct": [85, 90], "spread_pct": [50, 60], "rr_ratio": [1.5, 2.0]},
        "notes": "",
    },
    {
        "key": "ofi_velocity",
        "family": "A_OFI",
        "name": "OFI Velocity (Rate of Change)",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10"],
        "hypothesis": "Accelerating OFI (rate of change positive) signals momentum build-up before price moves",
        "entry_logic": "ofi_5_change > rolling_quantile(90th) AND ofi_5 > 0; rate-of-change filter",
        "exit_logic": "ATR stop and target; timeout",
        "risk_model": "ATR stop, RR, exclusivity",
        "features_required": ["ofi_5", "ofi_5_lag1"],
        "lookahead_risks": ["both OFI values computed from past bars"],
        "failure_modes": ["noisy second derivative; many false signals from tick-by-tick OFI volatility"],
        "param_grid": {"ofi_chg_pct": [85, 90], "rr_ratio": [1.5, 2.0], "hold_bars": [5, 10]},
        "notes": "Velocity adds temporal dimension to plain OFI threshold crossing.",
    },
    {
        "key": "ofi_divergence_fade",
        "family": "A_OFI",
        "name": "OFI-Price Divergence Fade",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min", "5min"],
        "data_required": ["mbp-10"],
        "hypothesis": "Price reaches new high while OFI weakening = buying exhausting; fade the move",
        "entry_logic": "close > N-bar high AND ofi_5 < ofi_5_lag_N (negative divergence); short entry",
        "exit_logic": "ATR stop; target at N-bar midpoint",
        "risk_model": "ATR stop, RR, exclusivity",
        "features_required": ["ofi_5", "close", "high"],
        "lookahead_risks": ["N-bar high uses prior bars only"],
        "failure_modes": ["divergence resolves upward in strong trends"],
        "param_grid": {"lookback": [5, 10], "rr_ratio": [1.5, 2.0]},
        "notes": "Contrarian; complement to OFI momentum strategies.",
    },
    {
        "key": "ofi_multi_level_depth",
        "family": "A_OFI",
        "name": "OFI + Full Depth Pressure",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10"],
        "hypothesis": "OFI on top levels combined with full book depth pressure (L1-L10 imbalance) = highest-conviction signal",
        "entry_logic": "ofi_5 > threshold AND sum of bid_size[1:10] > sum of ask_size[1:10] by > X%",
        "exit_logic": "ATR stop and target",
        "risk_model": "ATR stop, RR, exclusivity",
        "features_required": ["ofi_5", "imbal_L5_mean", "imbal_L5_last"],
        "lookahead_risks": ["both features computed at bar close from prior ticks"],
        "failure_modes": ["composite threshold may be too strict; very low trade count"],
        "param_grid": {"ofi_pct": [80, 85], "imbal_thr": [0.3, 0.4], "rr_ratio": [1.5, 2.0]},
        "notes": "Requires both OFI and depth data available simultaneously.",
    },
    # ── Family B: Depth / Queue ────────────────────────────────────────────────
    {
        "key": "depth_l1_imbalance_momentum",
        "family": "B_DEPTH",
        "name": "L1 Depth Imbalance Momentum",
        "priority": 1,
        "status": "survivor",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10"],
        "hypothesis": "Large bid/ask size ratio at L1 → price will follow the dominant side",
        "entry_logic": "imbal_L1 > rolling_quantile(90th); sustained for persist_bars",
        "exit_logic": "ATR stop and target; timeout",
        "risk_model": "ATR stop, RR, 1-contract exclusivity",
        "features_required": ["imbal_L5_last", "imbal_L5_mean"],
        "lookahead_risks": ["imbalance column must not include current bar's final state"],
        "failure_modes": ["overlapping positions if position exclusivity not enforced (now fixed)", "imbalance signals cluster — de-clustering needed"],
        "param_grid": {"imbal_thr": [0.3, 0.4, 0.5], "persist_bars": [2, 3, 5], "rr_ratio": [2.0], "hold_bars": [5, 10]},
        "notes": "REHABILITATED 2026-06-03 after position exclusivity fix + news filter. GC: WF Sharpe 3.7-4.5, 3-tick resilient. SI: WF Sharpe 2.7-3.6.",
    },
    {
        "key": "depth_l5_trend_confirm",
        "family": "B_DEPTH",
        "name": "L5 Depth Imbalance Trend Confirm",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10"],
        "hypothesis": "Sustained L5 imbalance in one direction, aligning with L1 → confirmation trend entry",
        "entry_logic": "imbal_L5_mean > threshold; imbal_L5_last > threshold; both same sign",
        "exit_logic": "ATR stop and target",
        "risk_model": "ATR stop, RR, exclusivity",
        "features_required": ["imbal_L5_last", "imbal_L5_mean"],
        "lookahead_risks": ["standard rolling window anchoring"],
        "failure_modes": ["correlated with L1 imbalance — low marginal value"],
        "param_grid": {"imbal_pct": [75, 85], "rr_ratio": [1.5, 2.0]},
        "notes": "",
    },
    {
        "key": "depth_replenishment_signal",
        "family": "B_DEPTH",
        "name": "Limit Order Replenishment",
        "priority": 1,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10"],
        "hypothesis": "Passive orders refilling rapidly after being consumed = strong resting demand; price will hold and bounce",
        "entry_logic": "imbal_L5_mean > threshold (sustained bids dominating) AND imbal_L5_last > prior bar imbal (replenishing); long entry",
        "exit_logic": "ATR stop; target",
        "risk_model": "ATR stop, RR, exclusivity",
        "features_required": ["imbal_L5_last", "imbal_L5_mean"],
        "lookahead_risks": ["both computed from prior bar book snapshots"],
        "failure_modes": ["cannot distinguish true replenishment from spoofing without tick-level data"],
        "param_grid": {"imbal_thr": [0.2, 0.3], "persist_bars": [2, 3], "rr_ratio": [1.5, 2.0]},
        "notes": "Conceptually related to Repeated_Replenishment GC survivor but computed from book imbalance not CVD.",
    },
    {
        "key": "depth_pulling_signal",
        "family": "B_DEPTH",
        "name": "Order Pulling / Liquidity Withdrawal",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10"],
        "hypothesis": "Large limit orders rapidly cancelled (book thins) = informed selling → price will drop",
        "entry_logic": "imbal_L5_mean drops sharply from prior bar (liquidity withdrawal on bid side); short after confirmation bar",
        "exit_logic": "ATR stop; target",
        "risk_model": "ATR stop, RR, exclusivity",
        "features_required": ["imbal_L5_mean", "imbal_L5_last"],
        "lookahead_risks": ["imbalance delta computed from prior two bars"],
        "failure_modes": ["pulling can be benign (MM adjusting quotes); needs volume confirmation"],
        "param_grid": {"imbal_drop": [0.2, 0.3], "rr_ratio": [1.5, 2.0]},
        "notes": "Contrarian to Replenishment — signals institutional risk-off.",
    },
    {
        "key": "depth_stacking_signal",
        "family": "B_DEPTH",
        "name": "Order Stacking at Key Level",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10"],
        "hypothesis": "Multiple price levels stacking large orders on one side = market maker defending a level; fade the approach",
        "entry_logic": "imbal_L5_last > high_threshold for multiple consecutive bars; fade if price approaches stacked side",
        "exit_logic": "Level breach as stop; ATR target",
        "risk_model": "Level-based stop",
        "features_required": ["imbal_L5_last", "imbal_L5_mean"],
        "lookahead_risks": ["stacking detection uses prior bars only"],
        "failure_modes": ["large stacked orders may be spoofed; spoofer pulls order at last moment"],
        "param_grid": {"imbal_thr": [0.5, 0.6], "persist_bars": [3, 5], "rr_ratio": [1.5, 2.0]},
        "notes": "High-conviction only when imbalance is extreme and sustained.",
    },
    # ── Family C: Sweep ────────────────────────────────────────────────────────
    {
        "key": "sweep_continuation",
        "family": "C_SWEEP",
        "name": "Sweep Continuation",
        "priority": 1,
        "status": "survivor",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["trades", "mbp-10"],
        "hypothesis": "Aggressive sweep of multiple price levels (iceberg executed) signals institutional demand → momentum follows",
        "entry_logic": "sweep event detected (large market order crossing N price levels); enter next bar in sweep direction",
        "exit_logic": "ATR stop and target; timeout",
        "risk_model": "ATR stop, RR, exclusivity",
        "features_required": ["cvd_delta", "sweep_size", "sweep_direction"],
        "lookahead_risks": ["sweep detection must complete before bar close"],
        "failure_modes": ["false sweeps from stop-gun sequences", "spoofing — large order appears then vanishes"],
        "param_grid": {"sweep_size_pct": [85, 90, 95], "rr_ratio": [1.5, 2.0], "hold_bars": [5, 10]},
        "notes": "WF Sharpe=5.109 on SI (full 5yr). Top-priority survivor. SI stronger than GC.",
    },
    {
        "key": "sweep_absorption_reversal",
        "family": "C_SWEEP",
        "name": "Sweep Absorption Reversal",
        "priority": 3,
        "status": "eliminated",
        "symbols": ["GC"],
        "timeframes": ["1min"],
        "data_required": ["trades", "mbp-10"],
        "hypothesis": "Large sweep absorbed by resting limit orders → aggressor exhausted → fade the sweep",
        "entry_logic": "sweep followed by price returning to sweep level within N bars",
        "exit_logic": "ATR stop and target",
        "risk_model": "ATR stop, RR, exclusivity",
        "features_required": ["cvd_delta", "sweep_size"],
        "lookahead_risks": ["absorption level computed in retrospect"],
        "failure_modes": ["RECENCY ARTIFACT on GC — only works in 2024-2025 data; absent from full 5-year walk-forward"],
        "param_grid": {},
        "notes": "ELIMINATED. Do not deploy. Strong recency artifact: WF Sharpe > 5 in 2024-2025 only.",
    },
    {
        "key": "sweep_momentum_extended",
        "family": "C_SWEEP",
        "name": "Sweep Momentum Extended Hold",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["trades", "mbp-10"],
        "hypothesis": "After a confirmed sweep, momentum persists longer than a short hold period — use trailing stop",
        "entry_logic": "sweep event confirmed; trailing ATR stop instead of fixed target",
        "exit_logic": "Trailing ATR stop (tightens as profit grows)",
        "risk_model": "Trailing ATR stop",
        "features_required": ["cvd_delta", "sweep_direction", "atr"],
        "lookahead_risks": ["sweep detection same as Sweep_Continuation"],
        "failure_modes": ["trailing stop gets hit on pullback before final target; lower win rate"],
        "param_grid": {"trail_mult": [1.0, 1.5, 2.0], "hold_bars": [10, 20]},
        "notes": "Extended hold variant of Sweep_Continuation — different R distribution.",
    },
    {
        "key": "sweep_failure_reversal",
        "family": "C_SWEEP",
        "name": "Failed Sweep Reversal",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["trades", "mbp-10"],
        "hypothesis": "A sweep that fails to follow through within N bars signals exhaustion → fade",
        "entry_logic": "sweep detected; close returns to within 0.5 ATR of sweep entry price within M bars; fade direction",
        "exit_logic": "ATR stop; target",
        "risk_model": "ATR stop, exclusivity",
        "features_required": ["cvd_delta", "sweep_direction", "atr"],
        "lookahead_risks": ["sweep failure defined on past M bars only"],
        "failure_modes": ["difficult to distinguish temporary pause from true failure"],
        "param_grid": {"fail_bars": [3, 5], "rr_ratio": [1.5, 2.0]},
        "notes": "Contrarian to Sweep_Continuation; expect lower win rate, higher R per trade.",
    },
    # ── Family D: Absorption ───────────────────────────────────────────────────
    {
        "key": "absorption_at_level",
        "family": "D_ABSORPTION",
        "name": "Passive Absorption at Key Level",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10", "trades"],
        "hypothesis": "Price attacks a level repeatedly; passive side absorbs each attack; when selling exhausted, buy the break",
        "entry_logic": "N attacks on same price level detected; each absorbed; enter on next touch with stop below level",
        "exit_logic": "Fixed R target; stop below absorbed level",
        "risk_model": "Level-based stop, fixed R",
        "features_required": ["imbal_L5_last", "price_level_visits"],
        "lookahead_risks": ["level must be computed from prior bars only"],
        "failure_modes": ["level detection is computationally expensive; may miss dynamic levels"],
        "param_grid": {"n_attacks": [2, 3], "rr_ratio": [1.5, 2.0]},
        "notes": "",
    },
    {
        "key": "absorption_failed_auction",
        "family": "D_ABSORPTION",
        "name": "Failed Auction Reversal",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["5min"],
        "data_required": ["ohlcv", "mbp-10"],
        "hypothesis": "Price probes above a key level but fails to trade volume there — no acceptance. Return below probe level is a strong short signal.",
        "entry_logic": "high > prior_high by > threshold; close back below prior_high; volume on probe bar below average; short entry",
        "exit_logic": "ATR stop above probe high; target at session midpoint",
        "risk_model": "Level-based stop above probe extreme",
        "features_required": ["high", "close", "volume", "prior_day_high"],
        "lookahead_risks": ["prior_day_high from closed session"],
        "failure_modes": ["true breakouts get stopped; market will eventually accept new levels"],
        "param_grid": {"probe_ticks": [2, 3, 5], "rr_ratio": [1.5, 2.0]},
        "notes": "Auction Market Theory concept; matches Sweep_Failure but at key price levels.",
    },
    {
        "key": "absorption_iceberg_detection",
        "family": "D_ABSORPTION",
        "name": "Iceberg Order Detection",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10", "trades"],
        "hypothesis": "Iceberg orders absorb aggressive flow while showing only a fraction at each price level — detected by volume-at-price repeatedly refreshing",
        "entry_logic": "cvd_delta strongly negative (sellers hitting) but price not falling = iceberg absorption on bid side; enter long above iceberg level",
        "exit_logic": "ATR stop; target at iceberg level + N×ATR",
        "risk_model": "Level stop below iceberg price",
        "features_required": ["cvd_delta", "imbal_L5_last", "atr"],
        "lookahead_risks": ["iceberg detection uses cumulative bar statistics"],
        "failure_modes": ["true seller iceberg vs. passive MM absorption hard to distinguish"],
        "param_grid": {"cvd_thr": [-0.3, -0.4], "imbal_thr": [0.3, 0.4], "rr_ratio": [2.0]},
        "notes": "Requires both CVD (trades) and book imbalance data.",
    },
    # ── Family E: CVD ─────────────────────────────────────────────────────────
    {
        "key": "cvd_vwap",
        "family": "E_CVD",
        "name": "CVD + VWAP Momentum",
        "priority": 1,
        "status": "survivor",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["trades", "mbp-10"],
        "hypothesis": "Cumulative Volume Delta above threshold + price above session VWAP → institutional buying confirmed → momentum",
        "entry_logic": "cvd_delta > rolling_quantile(cvd_pct); close > session_vwap; combined filter",
        "exit_logic": "ATR stop and target; timeout",
        "risk_model": "ATR stop, RR, exclusivity",
        "features_required": ["cvd_delta", "session_vwap", "atr"],
        "lookahead_risks": ["CVD is cumulative — no bar-level lookahead risk; VWAP is session-level"],
        "failure_modes": ["CVD drifts structurally in trending markets; percentile threshold becomes biased"],
        "param_grid": {"cvd_pct": [70, 80, 90], "rr_ratio": [1.5, 2.0], "hold_bars": [5, 10]},
        "notes": "Survivor on GC (Sharpe 0.847 at 1T) and SI (Sharpe 0.623 at 1T). GC stronger.",
    },
    {
        "key": "cvd_microprice",
        "family": "E_CVD",
        "name": "CVD + Microprice Alignment",
        "priority": 1,
        "status": "survivor",
        "symbols": ["SI"],
        "timeframes": ["1min"],
        "data_required": ["trades", "mbp-10"],
        "hypothesis": "CVD bullish AND microprice above close → book-weighted mid confirms demand → enter long",
        "entry_logic": "cvd_delta > rolling_quantile(cvd_pct); microprice_last > close; rr_ratio and hold_bars tunable",
        "exit_logic": "ATR stop and target; timeout",
        "risk_model": "ATR stop, RR, exclusivity",
        "features_required": ["cvd_delta", "microprice_last", "atr"],
        "lookahead_risks": ["microprice is a live snapshot of the book — OK as long as computed at bar close"],
        "failure_modes": ["microprice mean-reverts quickly — needs tight entry timing"],
        "param_grid": {"cvd_pct": [60, 70, 80], "mp_mult": [0.5, 1.0, 1.5], "rr_ratio": [1.5, 2.0]},
        "notes": "BEST SLIPPAGE RESILIENCE: rr=2.0 variant survives 3-tick (Sharpe 0.935). SI only.",
    },
    {
        "key": "cvd_acceleration",
        "family": "E_CVD",
        "name": "CVD Acceleration",
        "priority": 1,
        "status": "survivor",
        "symbols": ["GC"],
        "timeframes": ["1min"],
        "data_required": ["trades", "mbp-10"],
        "hypothesis": "Accelerating CVD (buying pressure increasing faster than before) predicts imminent price breakout before it materialises",
        "entry_logic": "cvd_delta_change > rolling_quantile(cvd_accel_pct); cvd_delta positive; book imbalance confirmation",
        "exit_logic": "ATR stop; target at RR ratio; timeout",
        "risk_model": "ATR stop, RR, exclusivity",
        "features_required": ["cvd_delta", "imbal_L5_last", "atr"],
        "lookahead_risks": ["CVD delta computed from prior bar; acceleration from two prior bars"],
        "failure_modes": ["acceleration is noisy; false signals in low-volume sessions"],
        "param_grid": {"cvd_pct": [70, 80, 90], "imbal_thr": [0.3, 0.4], "rr_ratio": [1.5, 2.0], "hold_bars": [5, 10]},
        "notes": "NEW SURVIVOR (2026-06-03): Stress DSR 0.52 on GC at 2-tick. WF Sharpe 2.8-3.4, DSR=1.000. GC only.",
    },
    {
        "key": "cvd_divergence_reversal",
        "family": "E_CVD",
        "name": "CVD-Price Divergence Reversal",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min", "5min"],
        "data_required": ["trades"],
        "hypothesis": "Price making new high while CVD declining = buying pressure diminishing → reversal",
        "entry_logic": "price > N-bar high; cvd_delta < cvd_delta N bars ago; short entry on confirmation bar",
        "exit_logic": "ATR stop; target at recent support",
        "risk_model": "ATR stop, RR, exclusivity",
        "features_required": ["cvd_delta", "high", "atr"],
        "lookahead_risks": ["divergence detection uses past bars only — safe"],
        "failure_modes": ["divergence can persist for many bars before resolving; whipsaw risk in trending markets"],
        "param_grid": {"lookback": [5, 10, 20], "rr_ratio": [1.5, 2.0]},
        "notes": "",
    },
    {
        "key": "cvd_session_reset",
        "family": "E_CVD",
        "name": "CVD Session Reset Breakout",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI", "ES"],
        "timeframes": ["1min"],
        "data_required": ["trades"],
        "hypothesis": "At session open, CVD resets. First large CVD move sets session direction — trade the continuation",
        "entry_logic": "within first 30 bars of session: cvd_delta crosses rolling quantile threshold; enter in CVD direction",
        "exit_logic": "Session-end close; ATR stop",
        "risk_model": "ATR stop, session-end exit, exclusivity",
        "features_required": ["cvd_delta", "session_bar_number"],
        "lookahead_risks": ["session bar number must be computed from timestamps, not lookahead"],
        "failure_modes": ["open-range volatility produces false signals; needs RTH filter"],
        "param_grid": {"cvd_pct": [70, 80], "session_bars": [30, 60]},
        "notes": "",
    },
    {
        "key": "cvd_flip_momentum",
        "family": "E_CVD",
        "name": "CVD Sign Flip with Acceleration",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["trades"],
        "hypothesis": "CVD crossing from negative to positive with accelerating rate of change = structural shift from net selling to buying → momentum entry",
        "entry_logic": "cvd_delta crosses 0 from below AND cvd_delta_change > 0 (accelerating); enter long",
        "exit_logic": "ATR stop; target",
        "risk_model": "ATR stop, RR",
        "features_required": ["cvd_delta", "cvd_delta_lag1"],
        "lookahead_risks": ["cross detected from prior two bars"],
        "failure_modes": ["many zero-crossings in choppy/low-vol sessions"],
        "param_grid": {"accel_pct": [70, 80], "rr_ratio": [1.5, 2.0], "hold_bars": [5, 10]},
        "notes": "Sign-flip variant adds regime-change signal to CVD momentum family.",
    },
    {
        "key": "cvd_multi_session_bias",
        "family": "E_CVD",
        "name": "CVD Multi-Session Directional Bias",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["trades"],
        "hypothesis": "Prior session's cumulative CVD direction sets bias for current session; trade with prior-session CVD direction on intraday signals",
        "entry_logic": "prior_session_cvd > 0 (net buying yesterday) AND today's 1m OFI or CVD positive → long only",
        "exit_logic": "ATR stop; target; session end",
        "risk_model": "ATR stop, session-biased directional filter",
        "features_required": ["cvd_delta", "session_vwap"],
        "lookahead_risks": ["prior session CVD computed from closed prior day"],
        "failure_modes": ["prior-session bias stale if gap or overnight event occurs"],
        "param_grid": {"bias_lookback_sessions": [1, 3], "rr_ratio": [1.5, 2.0]},
        "notes": "Higher-timeframe CVD filter on intraday signals.",
    },
    # ── Family F: VWAP ────────────────────────────────────────────────────────
    {
        "key": "vwap_reclaim",
        "family": "F_VWAP",
        "name": "VWAP Reclaim",
        "priority": 1,
        "status": "survivor",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min", "5min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Price reclaims VWAP after dropping below → institutional acceptance above → momentum continuation",
        "entry_logic": "close crosses above session_vwap; prior bar close was below; enter long next bar",
        "exit_logic": "ATR stop and target; timeout",
        "risk_model": "ATR stop, RR",
        "features_required": ["session_vwap", "atr"],
        "lookahead_risks": ["VWAP at current bar includes current bar volume — minor; use prior bar VWAP"],
        "failure_modes": ["VWAP flat markets produce repeated crosses with no follow-through"],
        "param_grid": {"rr_ratio": [1.5, 2.0, 2.5], "hold_bars": [10, 20]},
        "notes": "Original OHLCV survivor from Step 1 stress testing.",
    },
    {
        "key": "vwap_deviation_mean_reversion",
        "family": "F_VWAP",
        "name": "VWAP Deviation Mean Reversion",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI", "ES"],
        "timeframes": ["5min", "15min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Prices > 1.5 standard deviations from VWAP tend to mean-revert within the session",
        "entry_logic": "abs(close - vwap) / vwap_std > deviation_threshold; fade the deviation",
        "exit_logic": "VWAP touch as exit; ATR stop",
        "risk_model": "VWAP stop, deviation-based entry",
        "features_required": ["session_vwap", "vwap_std"],
        "lookahead_risks": ["VWAP std computed from session start to current bar"],
        "failure_modes": ["trending sessions: VWAP deviates persistently; mean reversion fails"],
        "param_grid": {"deviation_mult": [1.5, 2.0, 2.5], "rr_ratio": [1.5, 2.0]},
        "notes": "",
    },
    {
        "key": "anchored_vwap_breakout",
        "family": "F_VWAP",
        "name": "Anchored VWAP Breakout",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI", "ES"],
        "timeframes": ["5min", "15min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Break above VWAP anchored to a key event (session open, FOMC, prior day close) with volume confirmation",
        "entry_logic": "close crosses anchored_vwap; volume spike in breakout bar",
        "exit_logic": "ATR stop; anchored VWAP as trailing stop floor",
        "risk_model": "ATR stop, trailing VWAP floor",
        "features_required": ["anchored_vwap", "volume"],
        "lookahead_risks": ["anchor event must be past timestamp"],
        "failure_modes": ["multiple competing VWAP anchors create ambiguous signals"],
        "param_grid": {"anchor": ["session_open", "prior_day_close"], "rr_ratio": [1.5, 2.0]},
        "notes": "",
    },
    {
        "key": "vwap_slope_momentum",
        "family": "F_VWAP",
        "name": "VWAP Slope Momentum",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI", "ES"],
        "timeframes": ["5min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Increasing VWAP slope indicates institutional accumulation in progress; buy dips to VWAP",
        "entry_logic": "vwap_slope > 0 AND slope_change > 0 (accelerating); close retests VWAP within 0.5 ATR; long entry",
        "exit_logic": "ATR stop below VWAP; target at N×ATR",
        "risk_model": "ATR stop, VWAP floor",
        "features_required": ["session_vwap", "atr"],
        "lookahead_risks": ["VWAP slope from prior two bars"],
        "failure_modes": ["VWAP slope computation sensitive to tick-level volume"],
        "param_grid": {"rr_ratio": [1.5, 2.0], "hold_bars": [5, 10]},
        "notes": "VWAP slope as regime indicator for intraday trend strength.",
    },
    {
        "key": "vwap_band_squeeze",
        "family": "F_VWAP",
        "name": "VWAP Band Squeeze Breakout",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI", "ES"],
        "timeframes": ["5min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Price hugging VWAP tightly for N bars (low ATR + close near VWAP) = coiling; first large departure signals breakout direction",
        "entry_logic": "ATR < rolling_quantile(20th) for N bars AND close near VWAP; breakout on bar close > VWAP + 1.5×ATR",
        "exit_logic": "ATR stop; target",
        "risk_model": "ATR stop",
        "features_required": ["session_vwap", "atr"],
        "lookahead_risks": ["ATR percentile from prior bars"],
        "failure_modes": ["false squeeze signals before major news; combine with news filter"],
        "param_grid": {"squeeze_bars": [5, 10], "breakout_mult": [1.0, 1.5], "rr_ratio": [1.5, 2.0]},
        "notes": "Volatility squeeze concept applied to VWAP proximity.",
    },
    # ── Family G: Multi-Timeframe ──────────────────────────────────────────────
    {
        "key": "mtf_ofi_trend_filter",
        "family": "G_MULTI_TF",
        "name": "Multi-Timeframe OFI Trend Filter",
        "priority": 1,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10"],
        "hypothesis": "1m OFI signal is more reliable when 5m OFI trend agrees — higher timeframe confirmation reduces noise",
        "entry_logic": "1m ofi_5 threshold exceeded AND 5m ofi_5 positive (same direction)",
        "exit_logic": "ATR stop; target; timeout",
        "risk_model": "ATR stop, RR, exclusivity",
        "features_required": ["ofi_5 at 1m and 5m"],
        "lookahead_risks": ["5m bar must be prior complete bar — no partial bar lookahead"],
        "failure_modes": ["5m OFI adds lag — misses fast moves in 1m timeframe"],
        "param_grid": {"ofi_1m_pct": [85, 90], "rr_ratio": [1.5, 2.0], "hold_bars": [5, 10]},
        "notes": "Priority 1 — builds on proven OFI foundation with minimal added complexity.",
    },
    {
        "key": "mtf_vwap_ofi",
        "family": "G_MULTI_TF",
        "name": "VWAP + OFI Dual Confirmation",
        "priority": 1,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10"],
        "hypothesis": "Price above VWAP (structural) AND OFI strongly positive (tactical) → highest-conviction longs",
        "entry_logic": "close > session_vwap AND ofi_5 > rolling_quantile(90th); combined entry",
        "exit_logic": "ATR stop; target",
        "risk_model": "ATR stop, RR",
        "features_required": ["ofi_5", "session_vwap", "atr"],
        "lookahead_risks": ["rolling quantile anchored to past bars"],
        "failure_modes": ["VWAP above price eliminates signals in downtrending days"],
        "param_grid": {"ofi_pct": [85, 90, 95], "rr_ratio": [1.5, 2.0]},
        "notes": "Natural extension of CVD_VWAP survivor.",
    },
    {
        "key": "mtf_sweep_ofi",
        "family": "G_MULTI_TF",
        "name": "Sweep + OFI Confirmation",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["trades", "mbp-10"],
        "hypothesis": "Sweep event on trades data confirmed by OFI on book data → multi-signal institutional move",
        "entry_logic": "sweep detected AND ofi_5 positive in sweep direction within 2 bars",
        "exit_logic": "ATR stop; target",
        "risk_model": "ATR stop, RR, exclusivity",
        "features_required": ["cvd_delta", "ofi_5"],
        "lookahead_risks": ["OFI and sweep must be detected from bars before entry"],
        "failure_modes": ["low trade count if both filters are strict"],
        "param_grid": {"sweep_pct": [85, 90], "ofi_pct": [70, 80], "rr_ratio": [1.5, 2.0]},
        "notes": "",
    },
    {
        "key": "mtf_depth_trend_confirmation",
        "family": "G_MULTI_TF",
        "name": "1m Depth Imbalance + 5m Trend",
        "priority": 1,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10"],
        "hypothesis": "Depth imbalance signal on 1m is more reliable when 5m price trend agrees — reduces false signals",
        "entry_logic": "1m imbal_L5_last > threshold AND 5m ema_slope > 0 (same direction); enter",
        "exit_logic": "ATR stop; target; timeout",
        "risk_model": "ATR stop, RR, exclusivity",
        "features_required": ["imbal_L5_last", "5m_ema"],
        "lookahead_risks": ["5m bar must be prior complete bar — no partial bar lookahead"],
        "failure_modes": ["5m EMA lags; confirmed trend = late entry on fast moves"],
        "param_grid": {"imbal_thr": [0.3, 0.4], "ema_period": [5, 10], "rr_ratio": [1.5, 2.0]},
        "notes": "Depth_Imbalance_Momentum rehabilitated — MTF version adds robustness.",
    },
    {
        "key": "mtf_cvd_cascade",
        "family": "G_MULTI_TF",
        "name": "CVD Cascade (1m + 5m + 15m Alignment)",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["trades"],
        "hypothesis": "When 1m, 5m, and 15m CVDs all positive simultaneously, institutional buying is confirmed at multiple timescales",
        "entry_logic": "cvd_1m > 0 AND cvd_5m > 0 AND cvd_15m > 0; all same direction; enter on 1m signal bar",
        "exit_logic": "ATR stop; target",
        "risk_model": "ATR stop, RR",
        "features_required": ["cvd_delta at 1m, 5m, 15m"],
        "lookahead_risks": ["each timeframe bar must be closed before use"],
        "failure_modes": ["very rare signals when all three agree strictly"],
        "param_grid": {"cvd_pct_1m": [60, 70], "cvd_pct_5m": [50, 60], "rr_ratio": [1.5, 2.0]},
        "notes": "Extreme selectivity — expect fewer but higher-quality trades.",
    },
    # ── Family H: Cross-Market ─────────────────────────────────────────────────
    {
        "key": "gc_si_ratio_mean_rev",
        "family": "H_CROSS_MARKET",
        "name": "Gold/Silver Ratio Mean Reversion",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["5min", "15min"],
        "data_required": ["ohlcv"],
        "hypothesis": "GC/SI ratio mean-reverts around a trailing mean; extreme ratio → pair trade toward mean",
        "entry_logic": "gc_si_ratio > mean + N×std → short GC long SI; ratio < mean - N×std → opposite",
        "exit_logic": "Ratio returns to mean; ATR stop on each leg",
        "risk_model": "Spread-based stop; equal dollar risk on each leg",
        "features_required": ["GC.close", "SI.close"],
        "lookahead_risks": ["rolling mean computed from past bars"],
        "failure_modes": ["ratio can trend for weeks during supply shocks (COVID, ETF flows)"],
        "param_grid": {"ratio_window": [20, 60, 120], "z_entry": [1.5, 2.0, 2.5]},
        "notes": "Personal broker required — two simultaneous positions. Prop firm risk.",
    },
    {
        "key": "dollar_gold_invert",
        "family": "H_CROSS_MARKET",
        "name": "Dollar/Gold Inversion",
        "priority": 3,
        "status": "pending",
        "symbols": ["GC"],
        "timeframes": ["5min"],
        "data_required": ["ohlcv", "DX futures"],
        "hypothesis": "GC and DX (dollar index) move inversely on a short timescale; DX momentum predicts GC direction",
        "entry_logic": "DX crosses below rolling mean → long GC; DX crosses above → short GC",
        "exit_logic": "ATR stop; timeout",
        "risk_model": "ATR stop, exclusivity",
        "features_required": ["DX.close", "GC.close"],
        "lookahead_risks": ["DX bar must be prior completed bar"],
        "failure_modes": ["correlation breaks down during risk-off episodes when both fall together"],
        "param_grid": {"dx_window": [5, 10, 20], "rr_ratio": [1.5, 2.0]},
        "notes": "Requires DX futures data — not yet downloaded.",
    },
    {
        "key": "oil_gold_lead_lag",
        "family": "H_CROSS_MARKET",
        "name": "Oil-Gold Lead-Lag",
        "priority": 3,
        "status": "pending",
        "symbols": ["GC"],
        "timeframes": ["15min"],
        "data_required": ["ohlcv", "CL futures"],
        "hypothesis": "Oil (CL) leads gold as an inflation proxy; large CL moves predict GC direction within 1-2 bars",
        "entry_logic": "CL 15m return > N×ATR → trade GC in same direction on next bar open",
        "exit_logic": "ATR stop; timeout",
        "risk_model": "ATR stop",
        "features_required": ["CL.close", "GC.close"],
        "lookahead_risks": ["CL bar must be closed before entry; no lookahead"],
        "failure_modes": ["lead-lag unstable across regimes (supply shocks vs. demand-driven moves)"],
        "param_grid": {"cl_move_mult": [1.0, 1.5], "rr_ratio": [1.5, 2.0]},
        "notes": "Requires CL futures data — not yet downloaded. Priority 3.",
    },
    # ── Family I: Calendar / Event ─────────────────────────────────────────────
    {
        "key": "fomc_drift",
        "family": "I_CALENDAR",
        "name": "FOMC Pre-Announcement Drift",
        "priority": 2,
        "status": "tested",
        "symbols": ["GC", "ES"],
        "timeframes": ["5min", "15min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Informed participants position in advance of FOMC. Systematic drift in the 2-4 hours before announcement.",
        "entry_logic": "2 hours before FOMC announcement time (2pm ET); enter in direction of prior 1-week trend",
        "exit_logic": "Close position at FOMC announcement; stop at 1% adverse move",
        "risk_model": "Time-based exit, tight stop",
        "features_required": ["fomc_time", "prior_week_return"],
        "lookahead_risks": ["FOMC date calendar must be historical — no look-ahead of rate decision"],
        "failure_modes": ["drift reverses if consensus positioning is wrong; unexpected surprise wipes gains"],
        "param_grid": {"entry_hours_before": [1, 2, 3], "rr_ratio": [1.5, 2.0]},
        "notes": "OHLCV-era survivor. Tested on ES and GC. See src/strategies/fomc_drift.py",
    },
    {
        "key": "nfp_reversal",
        "family": "I_CALENDAR",
        "name": "NFP Announcement Reversal",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "ES"],
        "timeframes": ["1min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Initial NFP spike overreacts; fade the move in the first 30 minutes for mean reversion",
        "entry_logic": "After 8:30 ET on NFP Friday: wait 2 bars for initial spike; fade the spike direction",
        "exit_logic": "Close before session close; ATR stop from spike extreme",
        "risk_model": "ATR stop from spike; time exit",
        "features_required": ["nfp_date", "open", "high", "low", "close"],
        "lookahead_risks": ["NFP date calendar is historical — no look-ahead of the number"],
        "failure_modes": ["if number is extreme (2020 COVID, 2021 jobs boom), spike continues for hours"],
        "param_grid": {"bars_wait": [1, 2, 3], "rr_ratio": [1.5, 2.0]},
        "notes": "",
    },
    {
        "key": "london_open_breakout",
        "family": "I_CALENDAR",
        "name": "London Open Breakout",
        "priority": 2,
        "status": "tested",
        "symbols": ["GC", "SI", "ES"],
        "timeframes": ["5min", "15min"],
        "data_required": ["ohlcv"],
        "hypothesis": "London open (3:00 AM ET) brings institutional volume; price breaks from Asia-session range",
        "entry_logic": "At London open: close > Asia session high → long; close < Asia session low → short",
        "exit_logic": "ATR stop; target at R multiple; session-end exit",
        "risk_model": "ATR stop, exclusivity",
        "features_required": ["asia_session_high", "asia_session_low", "atr"],
        "lookahead_risks": ["Asia session range computed from closed bars only"],
        "failure_modes": ["fakeout breakouts before true direction established"],
        "param_grid": {"rr_ratio": [1.5, 2.0], "hold_bars": [20, 40]},
        "notes": "See src/strategies/london_open_breakout.py",
    },
    {
        "key": "cpi_pre_positioning",
        "family": "I_CALENDAR",
        "name": "CPI Pre-Announcement Drift",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["15min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Informed participants position gold before CPI releases (8:30 ET ~12th of month); systematic 2-hour pre-drift",
        "entry_logic": "2 hours before CPI announcement: enter in direction of 1-week gold trend; exit at announcement",
        "exit_logic": "Time-based exit at 8:30 ET; stop at 1% adverse",
        "risk_model": "Time-based exit, hard stop",
        "features_required": ["cpi_time", "prior_week_return"],
        "lookahead_risks": ["CPI date calendar is historical; no look-ahead of the number"],
        "failure_modes": ["surprise CPI prints cause spike against position"],
        "param_grid": {"entry_hours_before": [1, 2], "rr_ratio": [1.5, 2.0]},
        "notes": "CPI dates now included in tick_news_filter.py event calendar.",
    },
    {
        "key": "quarter_end_rebalancing",
        "family": "I_CALENDAR",
        "name": "Quarter-End Rebalancing Flow",
        "priority": 3,
        "status": "pending",
        "symbols": ["GC", "ES"],
        "timeframes": ["15min", "30min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Last 3 days of each quarter, institutional rebalancing creates predictable directional pressure",
        "entry_logic": "Last 3 days of quarter: if GC up strongly YTD → fade (profit-taking); if GC down → buy (rebalance into gold)",
        "exit_logic": "Quarter end close; ATR stop",
        "risk_model": "Time-based exit",
        "features_required": ["quarter_end_date", "ytd_return"],
        "lookahead_risks": ["YTD return computed from prior close only"],
        "failure_modes": ["rebalancing effect may be priced in earlier by forward-looking participants"],
        "param_grid": {"days_before_qend": [1, 2, 3]},
        "notes": "Priority 3 — calendar effect; needs long backtest to validate.",
    },
    # ── Family J: Trend Following ──────────────────────────────────────────────
    {
        "key": "donchian_breakout",
        "family": "J_TREND",
        "name": "Donchian Channel Breakout",
        "priority": 2,
        "status": "tested",
        "symbols": ["GC", "SI", "ES", "CL"],
        "timeframes": ["15min", "30min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Breakout from N-period high/low signals sustained directional momentum",
        "entry_logic": "close > highest_high(N); enter long. close < lowest_low(N); enter short",
        "exit_logic": "ATR trailing stop; time stop",
        "risk_model": "ATR trailing stop",
        "features_required": ["high", "low", "close", "atr"],
        "lookahead_risks": ["channel uses prior N bars only"],
        "failure_modes": ["whipsaws in ranging markets; requires trend regime filter"],
        "param_grid": {"channel_len": [20, 40, 60], "rr_ratio": [2.0, 3.0]},
        "notes": "See src/strategies/donchian_breakout.py",
    },
    {
        "key": "vol_adj_momentum",
        "family": "J_TREND",
        "name": "Volatility-Adjusted Momentum",
        "priority": 2,
        "status": "tested",
        "symbols": ["GC", "SI", "ES"],
        "timeframes": ["15min", "30min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Momentum signal scaled by recent volatility — stronger in low-vol conditions, muted in high-vol",
        "entry_logic": "N-bar return / ATR > threshold; direction of momentum; ATR regime filter",
        "exit_logic": "ATR stop; time stop",
        "risk_model": "Volatility-scaled stop",
        "features_required": ["close", "atr"],
        "lookahead_risks": ["return computed from N bars ago — safe"],
        "failure_modes": ["momentum reverses quickly in choppy gold markets"],
        "param_grid": {"lookback": [5, 10, 20], "vol_threshold": [0.5, 1.0, 1.5]},
        "notes": "See src/strategies/vol_adj_momentum.py",
    },
    {
        "key": "keltner_breakout",
        "family": "J_TREND",
        "name": "Keltner Channel Breakout",
        "priority": 2,
        "status": "tested",
        "symbols": ["GC", "SI", "ES"],
        "timeframes": ["15min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Breakout above Keltner upper band (EMA + N×ATR) in high-volume bar signals institutional momentum",
        "entry_logic": "close > keltner_upper AND volume > N-bar average; enter long",
        "exit_logic": "Keltner midline as exit; ATR stop",
        "risk_model": "ATR stop",
        "features_required": ["close", "atr", "ema"],
        "lookahead_risks": ["Keltner bands computed from prior bars"],
        "failure_modes": ["false breakouts in low-vol drift"],
        "param_grid": {"atr_mult": [1.5, 2.0, 2.5], "ema_len": [20, 40]},
        "notes": "See src/strategies/keltner_breakout.py",
    },
    {
        "key": "adx_momentum_filter",
        "family": "J_TREND",
        "name": "ADX Trend Strength Filter",
        "priority": 2,
        "status": "tested",
        "symbols": ["GC", "SI", "ES"],
        "timeframes": ["15min"],
        "data_required": ["ohlcv"],
        "hypothesis": "ADX > 25 confirms trending market; only take momentum breakouts when ADX confirms trend strength",
        "entry_logic": "ADX > 25 (trending); +DI > -DI → long breakout; -DI > +DI → short breakout",
        "exit_logic": "ADX drops below 20 (trend ends); ATR stop",
        "risk_model": "ADX regime filter + ATR stop",
        "features_required": ["adx", "plus_di", "minus_di", "atr"],
        "lookahead_risks": ["ADX computed from prior bars only"],
        "failure_modes": ["ADX lags by 14+ bars; entry is late relative to trend start"],
        "param_grid": {"adx_period": [14], "adx_threshold": [20, 25], "rr_ratio": [2.0, 3.0]},
        "notes": "Trend-mode filter — reduces whipsaw in momentum strategies.",
    },
    {
        "key": "supertrend_momentum",
        "family": "J_TREND",
        "name": "Supertrend Indicator",
        "priority": 2,
        "status": "tested",
        "symbols": ["GC", "SI", "ES"],
        "timeframes": ["15min", "30min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Supertrend (ATR-based trailing band) provides clean trend direction signals with built-in stops",
        "entry_logic": "Supertrend flips from resistance to support (crossover); enter in flip direction",
        "exit_logic": "Supertrend flips back; trailing ATR band as stop",
        "risk_model": "Supertrend band as adaptive trailing stop",
        "features_required": ["close", "high", "low", "atr"],
        "lookahead_risks": ["Supertrend computed from prior bars only"],
        "failure_modes": ["choppy markets produce repeated flips; high turnover, negative edge"],
        "param_grid": {"atr_mult": [2.0, 3.0], "atr_period": [10, 14]},
        "notes": "Popular retail indicator; test to verify it adds value beyond plain ATR breakout.",
    },
    {
        "key": "ema_crossover_volume",
        "family": "J_TREND",
        "name": "EMA Crossover with Volume Confirmation",
        "priority": 2,
        "status": "tested",
        "symbols": ["GC", "SI", "ES"],
        "timeframes": ["5min", "15min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Fast EMA crossing slow EMA with above-average volume = institutional participation confirming the trend",
        "entry_logic": "ema_fast crosses above ema_slow AND volume > N-bar average × 1.5; enter long",
        "exit_logic": "EMA cross reversal; ATR stop",
        "risk_model": "ATR stop",
        "features_required": ["ema_fast", "ema_slow", "volume"],
        "lookahead_risks": ["both EMAs computed from prior bars"],
        "failure_modes": ["volume spike on news events creates false signals; news filter needed"],
        "param_grid": {"fast_period": [5, 8], "slow_period": [20, 34], "vol_mult": [1.5, 2.0]},
        "notes": "Classic but needs volume confirmation to reduce false signals.",
    },
    # ── Family K: Mean Reversion ───────────────────────────────────────────────
    {
        "key": "bollinger_rsi_meanrev",
        "family": "K_MEAN_REV",
        "name": "Bollinger Band + RSI Mean Reversion",
        "priority": 2,
        "status": "tested",
        "symbols": ["GC", "SI", "ES"],
        "timeframes": ["5min", "15min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Price touches lower Bollinger Band while RSI is oversold → mean reversion entry",
        "entry_logic": "close < BB_lower AND RSI < 30 → long; close > BB_upper AND RSI > 70 → short",
        "exit_logic": "BB midline as target; ATR stop",
        "risk_model": "ATR stop, BB-midline target",
        "features_required": ["bb_upper", "bb_lower", "bb_mid", "rsi"],
        "lookahead_risks": ["BB and RSI computed from prior bars"],
        "failure_modes": ["trending markets: oversold gets more oversold"],
        "param_grid": {"bb_period": [20, 40], "rsi_period": [14], "rr_ratio": [1.5, 2.0]},
        "notes": "See src/strategies/bollinger_rsi.py",
    },
    {
        "key": "overnight_fade",
        "family": "K_MEAN_REV",
        "name": "Overnight Gap Fade",
        "priority": 2,
        "status": "tested",
        "symbols": ["GC", "ES", "NQ"],
        "timeframes": ["5min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Large overnight gaps fill partially or fully in the first session hour",
        "entry_logic": "gap > N×ATR at open; fade gap direction; exit when gap filled or time stop",
        "exit_logic": "Gap fill; ATR stop",
        "risk_model": "ATR stop; time-based exit",
        "features_required": ["prior_close", "open", "atr"],
        "lookahead_risks": ["prior close from closed prior session bar"],
        "failure_modes": ["gaps following major news (FOMC, NFP) often don't fill"],
        "param_grid": {"gap_atr_mult": [1.0, 1.5, 2.0], "hold_bars": [20, 40]},
        "notes": "See src/strategies/overnight_fade.py",
    },
    {
        "key": "round_number_bounce",
        "family": "K_MEAN_REV",
        "name": "Round Number Support/Resistance",
        "priority": 3,
        "status": "pending",
        "symbols": ["GC"],
        "timeframes": ["1min", "5min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Gold prices cluster around round numbers ($50, $100 intervals). Approaches to these levels are faded.",
        "entry_logic": "close approaches within 0.5% of round number; volume increasing; fade the approach",
        "exit_logic": "Mean revert to midpoint of prior range; ATR stop",
        "risk_model": "ATR stop",
        "features_required": ["close", "atr", "volume"],
        "lookahead_risks": ["round number is deterministic — no lookahead"],
        "failure_modes": ["round numbers break on high-momentum days"],
        "param_grid": {"round_interval": [50, 100], "proximity_pct": [0.3, 0.5]},
        "notes": "",
    },
    {
        "key": "zscore_mean_reversion",
        "family": "K_MEAN_REV",
        "name": "Z-Score Mean Reversion",
        "priority": 2,
        "status": "tested",
        "symbols": ["GC", "SI", "ES"],
        "timeframes": ["5min", "15min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Price more than N standard deviations from rolling mean statistically reverts within session",
        "entry_logic": "zscore = (close - rolling_mean(N)) / rolling_std(N); abs(zscore) > threshold → fade direction",
        "exit_logic": "zscore returns to 0 (price at mean); ATR stop",
        "risk_model": "ATR stop, mean as target",
        "features_required": ["close", "rolling_mean", "rolling_std"],
        "lookahead_risks": ["rolling mean/std computed from prior N bars"],
        "failure_modes": ["trending markets: zscore remains extreme for many bars"],
        "param_grid": {"zscore_window": [20, 40], "zscore_threshold": [1.5, 2.0, 2.5], "rr_ratio": [1.5, 2.0]},
        "notes": "Simple but powerful mean reversion in ranging markets.",
    },
    {
        "key": "high_low_channel_fade",
        "family": "K_MEAN_REV",
        "name": "N-Bar High/Low Channel Fade",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["5min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Price touching N-bar high within session often fails to hold if volume is below average; fade the touch",
        "entry_logic": "close > rolling_max(high, N) AND volume < average volume × 0.8; short entry",
        "exit_logic": "ATR stop above channel; target at midpoint",
        "risk_model": "Channel-based stop",
        "features_required": ["high", "low", "close", "volume"],
        "lookahead_risks": ["channel computed from prior N bars"],
        "failure_modes": ["breakouts on volume spikes are real; volume filter critical"],
        "param_grid": {"channel_len": [20, 40], "vol_ratio": [0.7, 0.8], "rr_ratio": [1.5, 2.0]},
        "notes": "Low-volume touch at channel boundary = weak breakout attempt.",
    },
    {
        "key": "rsi_divergence_entry",
        "family": "K_MEAN_REV",
        "name": "RSI Divergence Entry",
        "priority": 2,
        "status": "tested",
        "symbols": ["GC", "SI", "ES"],
        "timeframes": ["5min", "15min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Price making new high/low while RSI makes lower high/higher low = momentum exhaustion → reversal",
        "entry_logic": "price > prior_swing_high AND RSI < prior_RSI_at_swing (negative divergence); enter short",
        "exit_logic": "ATR stop; target at prior swing support",
        "risk_model": "ATR stop",
        "features_required": ["rsi", "high", "low"],
        "lookahead_risks": ["swing detection from prior bars only"],
        "failure_modes": ["divergence can persist through multiple swings in strong trends"],
        "param_grid": {"rsi_period": [14], "lookback_swings": [2, 3], "rr_ratio": [1.5, 2.0]},
        "notes": "Classic reversal signal; needs careful swing point detection.",
    },
    # ── Family L: Opening Range Breakout ──────────────────────────────────────
    {
        "key": "rth_orb",
        "family": "L_ORB",
        "name": "RTH Opening Range Breakout",
        "priority": 2,
        "status": "tested",
        "symbols": ["ES", "NQ", "GC"],
        "timeframes": ["5min"],
        "data_required": ["ohlcv"],
        "hypothesis": "The first N minutes of RTH session set a reference range; breakout signals directional intent",
        "entry_logic": "After N-minute opening range: close > range_high → long; close < range_low → short",
        "exit_logic": "Range width as stop; target at 2× range width; session-end exit",
        "risk_model": "Range-based stop",
        "features_required": ["rth_open_high", "rth_open_low", "session_bar_number"],
        "lookahead_risks": ["opening range closes at N-minute mark; entry on bar N+1"],
        "failure_modes": ["fakeouts on NFP, FOMC days; needs news filter"],
        "param_grid": {"or_minutes": [15, 30, 60], "rr_ratio": [1.5, 2.0]},
        "notes": "See src/strategies/rth_orb.py. News filter now available.",
    },
    {
        "key": "prior_day_hl_sweep",
        "family": "L_ORB",
        "name": "Prior Day High/Low Sweep Reversal",
        "priority": 2,
        "status": "tested",
        "symbols": ["GC", "ES", "NQ"],
        "timeframes": ["5min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Price sweeps prior day high/low (stop hunt) then reverses — fade the sweep",
        "entry_logic": "price wick beyond prior day high/low AND close back inside range; enter fade on close",
        "exit_logic": "Prior day midpoint as target; ATR stop",
        "risk_model": "ATR stop",
        "features_required": ["prior_day_high", "prior_day_low", "atr"],
        "lookahead_risks": ["prior day H/L from closed prior session"],
        "failure_modes": ["sweeps followed by sustained breakouts on trend days"],
        "param_grid": {"sweep_pct": [0.1, 0.2, 0.3], "rr_ratio": [1.5, 2.0]},
        "notes": "See src/strategies/prior_day_hl_sweep.py",
    },
    {
        "key": "initial_balance_breakout",
        "family": "L_ORB",
        "name": "Initial Balance (First Hour) Breakout",
        "priority": 2,
        "status": "tested",
        "symbols": ["ES", "NQ", "GC"],
        "timeframes": ["5min"],
        "data_required": ["ohlcv"],
        "hypothesis": "The first hour of RTH (Initial Balance) sets the day's reference range; breakout beyond IB is directional for the full session",
        "entry_logic": "After 10:30 ET: close > IB_high → long; close < IB_low → short; volume confirmation",
        "exit_logic": "Session close; ATR stop; target at IB width × 1.5",
        "risk_model": "IB-based stop",
        "features_required": ["ib_high", "ib_low", "session_bar_number"],
        "lookahead_risks": ["IB computed from 9:30-10:30 ET bars only"],
        "failure_modes": ["IB breakouts fail on low-volatility or holiday-session days"],
        "param_grid": {"ib_minutes": [60], "rr_ratio": [1.5, 2.0, 2.5]},
        "notes": "CME Globex IB differs from RTH IB; use RTH IB for gold futures.",
    },
    {
        "key": "asia_range_fade_rth",
        "family": "L_ORB",
        "name": "Asia Range Fade at RTH Open",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["5min"],
        "data_required": ["ohlcv"],
        "hypothesis": "If RTH opens inside Asia session range, price tends to probe range extremes and fade",
        "entry_logic": "RTH open inside Asia range; close approaches Asia session high → short; close approaches low → long",
        "exit_logic": "Asia midpoint as target; ATR stop",
        "risk_model": "ATR stop, Asia range floor/ceiling",
        "features_required": ["asia_session_high", "asia_session_low", "atr"],
        "lookahead_risks": ["Asia range from closed Asia bars"],
        "failure_modes": ["RTH can break out of Asia range on fundamental news"],
        "param_grid": {"proximity_pct": [0.2, 0.3], "rr_ratio": [1.5, 2.0]},
        "notes": "Complement to London Open Breakout — RTH fade variant.",
    },
    # ── Family M: ML / Composite ──────────────────────────────────────────────
    {
        "key": "ml_feature_ensemble",
        "family": "M_ML",
        "name": "L2 Feature Ensemble (ML)",
        "priority": 3,
        "status": "research",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10", "trades"],
        "hypothesis": "A gradient boosted classifier on all L2 features (OFI, imbalance, microprice, CVD, spread) may capture non-linear interactions",
        "entry_logic": "Classifier probability > threshold; direction from predicted class",
        "exit_logic": "ATR stop; probability drop below threshold",
        "risk_model": "ATR stop, probability gate",
        "features_required": ["ofi_1", "ofi_5", "imbal_L5_last", "imbal_L5_mean", "microprice_last", "spread_mean", "cvd_delta", "atr"],
        "lookahead_risks": ["train/test split must be time-series aware (no shuffle split)", "all features computed on past bars only"],
        "failure_modes": ["overfitting on non-stationary L2 data", "feature importance unstable"],
        "param_grid": {"n_estimators": [100, 200], "max_depth": [3, 5], "min_samples_leaf": [50, 100]},
        "notes": "Priority 3 — requires significant careful implementation. Do not rush.",
    },
    {
        "key": "ofi_regime_adaptive",
        "family": "M_ML",
        "name": "OFI with Regime Conditioning",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10"],
        "hypothesis": "OFI signal has higher accuracy in trending regimes than ranging regimes",
        "entry_logic": "OFI threshold exceeded AND regime classifier in 'trending' state",
        "exit_logic": "ATR stop; target",
        "risk_model": "ATR stop, RR",
        "features_required": ["ofi_5", "atr", "rolling_return_std"],
        "lookahead_risks": ["regime detector uses past N bars only"],
        "failure_modes": ["regime classifier lags regime changes"],
        "param_grid": {"ofi_pct": [85, 90], "regime_window": [60, 120]},
        "notes": "",
    },
    {
        "key": "online_learning_adaptive",
        "family": "M_ML",
        "name": "Online Learning Adaptive Model",
        "priority": 3,
        "status": "research",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10", "trades"],
        "hypothesis": "An online-learning model (River / Vowpal Wabbit) that continuously updates from recent trades adapts to regime changes faster than batch-trained models",
        "entry_logic": "Online classifier predicts direction with probability > threshold; update model after each trade outcome",
        "exit_logic": "ATR stop; probability drop; timeout",
        "risk_model": "ATR stop + probability gate",
        "features_required": ["ofi_5", "cvd_delta", "imbal_L5_last", "atr"],
        "lookahead_risks": ["model must only train on data up to current bar"],
        "failure_modes": ["model can learn noise and overfit to recent moves"],
        "param_grid": {"learning_rate": [0.01, 0.05], "window": [500, 1000]},
        "notes": "Priority 3 — requires River library; complex to backtest correctly.",
    },
    # ── Family N: Spread Dynamics ──────────────────────────────────────────────
    {
        "key": "bid_ask_spread_compression",
        "family": "N_SPREAD",
        "name": "Bid-Ask Spread Compression Momentum",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10"],
        "hypothesis": "Tight spreads (below average) indicate active market-maker competition and liquid conditions; momentum signals more reliable",
        "entry_logic": "spread_mean < rolling_quantile(spread, 30th) AND OFI threshold exceeded; enter",
        "exit_logic": "ATR stop; target",
        "risk_model": "ATR stop, exclusivity",
        "features_required": ["spread_mean", "ofi_5"],
        "lookahead_risks": ["spread percentile from prior bars"],
        "failure_modes": ["tight spread filter eliminates too many signals in normal GC tick structure"],
        "param_grid": {"spread_pct": [30, 40], "ofi_pct": [85, 90], "rr_ratio": [1.5, 2.0]},
        "notes": "Liquidity-filtered version of OFI strategy.",
    },
    {
        "key": "spread_widening_reversal",
        "family": "N_SPREAD",
        "name": "Spread Widening Reversal",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10"],
        "hypothesis": "Sudden spread widening (MMs pulling quotes) signals uncertainty; fade the prevailing direction",
        "entry_logic": "spread_mean > rolling_quantile(spread, 80th) AND close moved > N×ATR from prior bar; fade the move",
        "exit_logic": "Spread normalises (returns below 60th pct); ATR stop",
        "risk_model": "ATR stop, spread normalisation exit",
        "features_required": ["spread_mean", "close", "atr"],
        "lookahead_risks": ["spread percentile from prior rolling window"],
        "failure_modes": ["spread stays wide in genuine breakout — reversal logic wrong"],
        "param_grid": {"spread_pct": [75, 80], "move_mult": [1.0, 1.5], "rr_ratio": [1.5, 2.0]},
        "notes": "Contrarian; most useful near end of fast moves.",
    },
    {
        "key": "effective_spread_direction",
        "family": "N_SPREAD",
        "name": "Effective Spread Direction Indicator",
        "priority": 3,
        "status": "research",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["trades", "mbp-10"],
        "hypothesis": "Effective spread (2×|trade_price - midprice|) direction reveals buyer/seller-initiated cost; direction with lower effective spread is the informed side",
        "entry_logic": "buyer_eff_spread < seller_eff_spread AND cvd > 0; enter long",
        "exit_logic": "ATR stop; target",
        "risk_model": "ATR stop",
        "features_required": ["trade_price", "microprice_last", "cvd_delta"],
        "lookahead_risks": ["effective spread computed from prior bar trades"],
        "failure_modes": ["requires tick-level data processing not in current bar aggregation"],
        "param_grid": {"eff_spread_pct": [40, 50], "rr_ratio": [1.5, 2.0]},
        "notes": "Research concept; requires careful microstructure analysis.",
    },
    # ── Family O: Microstructure ──────────────────────────────────────────────
    {
        "key": "trade_arrival_acceleration",
        "family": "O_MICROSTRUCTURE",
        "name": "Trade Arrival Rate Acceleration",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["trades"],
        "hypothesis": "Accelerating trade arrival rate (more trades per minute than prior bars) signals imminent directional move — institutional flow starting to hit market",
        "entry_logic": "trade_count > rolling_quantile(trade_count, 90th) AND cvd positive; enter in CVD direction",
        "exit_logic": "ATR stop; target; timeout",
        "risk_model": "ATR stop, RR, exclusivity",
        "features_required": ["trade_count_per_bar", "cvd_delta"],
        "lookahead_risks": ["trade count computed from closed bar"],
        "failure_modes": ["high trade count on news events = false signal without news filter"],
        "param_grid": {"count_pct": [80, 85, 90], "rr_ratio": [1.5, 2.0], "hold_bars": [5, 10]},
        "notes": "Trade intensity as microstructure signal.",
    },
    {
        "key": "trade_size_skew",
        "family": "O_MICROSTRUCTURE",
        "name": "Trade Size Skew (Large vs Small)",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["trades"],
        "hypothesis": "When large trades dominate vs small trades, institutional activity drives direction; small trade dominance = retail noise",
        "entry_logic": "large_trade_ratio > threshold AND direction of large trades = cvd direction; enter",
        "exit_logic": "ATR stop; target",
        "risk_model": "ATR stop, RR",
        "features_required": ["trade_size_large", "trade_size_small", "cvd_delta"],
        "lookahead_risks": ["large/small trade split from closed bar trades"],
        "failure_modes": ["defining 'large' vs 'small' threshold requires symbol-specific calibration"],
        "param_grid": {"large_trade_size": [10, 20, 50], "ratio_threshold": [0.6, 0.7], "rr_ratio": [1.5, 2.0]},
        "notes": "Trade size decomposition to identify institutional vs retail flow.",
    },
    {
        "key": "price_impact_asymmetry",
        "family": "O_MICROSTRUCTURE",
        "name": "Price Impact Asymmetry",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["trades", "mbp-10"],
        "hypothesis": "If buy-initiated trades move price more per unit volume than sell-initiated trades, informed buyers are present → enter long",
        "entry_logic": "buy_impact_per_vol > sell_impact_per_vol by threshold; enter long",
        "exit_logic": "ATR stop; target",
        "risk_model": "ATR stop",
        "features_required": ["cvd_delta", "trade_size", "close"],
        "lookahead_risks": ["impact computed from prior bar trade-by-trade data"],
        "failure_modes": ["impact asymmetry requires precise tick-by-tick aggregation"],
        "param_grid": {"asymmetry_ratio": [1.3, 1.5], "rr_ratio": [1.5, 2.0]},
        "notes": "Requires tick-level trade price impact computation — advanced feature.",
    },
    {
        "key": "queue_position_estimate",
        "family": "O_MICROSTRUCTURE",
        "name": "Estimated Queue Position",
        "priority": 3,
        "status": "research",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min"],
        "data_required": ["mbp-10", "trades"],
        "hypothesis": "MBO data allows estimating queue position on a limit order. Better queue position = higher fill probability at lower adverse selection cost.",
        "entry_logic": "Not a standalone strategy — a fill-quality optimizer for other strategies that use limit orders",
        "exit_logic": "N/A",
        "risk_model": "N/A — queue position is an execution parameter not a strategy",
        "features_required": ["bid_size_L1", "ask_size_L1", "trade_count"],
        "lookahead_risks": ["queue position estimate must use prior bar book state"],
        "failure_modes": ["MBO data (Databento MBO schema) not yet downloaded"],
        "param_grid": {},
        "notes": "Priority 3 — requires MBO schema data; significant infrastructure investment.",
    },
    # ── Family P: Statistical Arbitrage ──────────────────────────────────────
    {
        "key": "calendar_spread_basis",
        "family": "P_STAT_ARB",
        "name": "GC Calendar Spread Basis",
        "priority": 3,
        "status": "pending",
        "symbols": ["GC"],
        "timeframes": ["15min"],
        "data_required": ["ohlcv"],
        "hypothesis": "GC front month vs. deferred month basis mean-reverts around cost-of-carry; deviations signal roll opportunity",
        "entry_logic": "basis = deferred_price - front_price - fair_carry; abs(basis) > N×std; fade the deviation",
        "exit_logic": "Basis returns to fair value; stop at 1.5×entry deviation",
        "risk_model": "Basis-based stop; equal-dollar both legs",
        "features_required": ["GC_front.close", "GC_deferred.close"],
        "lookahead_risks": ["fair carry is deterministic (interest rate known)"],
        "failure_modes": ["delivery month squeeze causes persistent basis deviation"],
        "param_grid": {"carry_rate": [0.05, 0.055], "dev_mult": [1.5, 2.0]},
        "notes": "Requires two GC contracts; prop firm may not support. Priority 3.",
    },
    {
        "key": "gc_si_futures_pair",
        "family": "P_STAT_ARB",
        "name": "GC-SI Cointegrated Pair",
        "priority": 3,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["15min"],
        "data_required": ["ohlcv"],
        "hypothesis": "GC and SI are cointegrated (both precious metals driven by inflation and dollar). Log-ratio deviations mean-revert.",
        "entry_logic": "zscore(log(GC/SI)) > 2.0 → short GC, long SI; zscore < -2.0 → opposite",
        "exit_logic": "zscore returns to 0; hard stop at zscore 3.0",
        "risk_model": "Equal-dollar exposure both legs; spread stop",
        "features_required": ["GC.close", "SI.close"],
        "lookahead_risks": ["rolling cointegration coefficient from prior window"],
        "failure_modes": ["pair can decouple on supply/demand shocks specific to one metal"],
        "param_grid": {"ratio_window": [60, 120], "zscore_entry": [1.5, 2.0]},
        "notes": "Two simultaneous positions — prop firm compliance issue. Priority 3.",
    },
    {
        "key": "ou_intraday_mean_reversion",
        "family": "P_STAT_ARB",
        "name": "Ornstein-Uhlenbeck Intraday Reversion",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["5min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Price within a single session follows an OU process with mean-reverting drift. Deviations beyond 2σ produce next-bar corrections.",
        "entry_logic": "Fit OU process to session price; enter when price > theta + 2σ or < theta - 2σ",
        "exit_logic": "Price returns to theta; stop at 3σ",
        "risk_model": "OU-based stop (3σ)",
        "features_required": ["close"],
        "lookahead_risks": ["OU parameters fit to prior N bars only"],
        "failure_modes": ["gold prices can trend persistently across sessions; OU assumption breaks down"],
        "param_grid": {"ou_window": [60, 120], "entry_sigma": [1.5, 2.0]},
        "notes": "Analytically rigorous; requires scipy.optimize for OU parameter fitting.",
    },
    # ── Family Q: Volume Profile ──────────────────────────────────────────────
    {
        "key": "poc_magnet_effect",
        "family": "Q_VOL_PROFILE",
        "name": "Point of Control Magnet",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI", "ES"],
        "timeframes": ["5min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Price tends to gravitate toward the prior session's Point of Control (highest volume price) when trading nearby",
        "entry_logic": "close within N×ATR of prior POC but on far side; enter toward POC",
        "exit_logic": "POC touch; ATR stop",
        "risk_model": "ATR stop",
        "features_required": ["prior_session_poc", "close", "atr"],
        "lookahead_risks": ["POC from prior closed session"],
        "failure_modes": ["POC attraction fails when current session has different profile shape"],
        "param_grid": {"poc_distance_atr": [0.5, 1.0], "rr_ratio": [1.5, 2.0]},
        "notes": "Volume Profile concept; requires OHLCV to compute volume-at-price histogram.",
    },
    {
        "key": "value_area_breakout",
        "family": "Q_VOL_PROFILE",
        "name": "Value Area High/Low Breakout",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI", "ES"],
        "timeframes": ["5min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Breaking above prior session's Value Area High (VAH) with volume = market acceptance at new prices",
        "entry_logic": "close > prior VAH AND volume > average; enter long. close < prior VAL → short",
        "exit_logic": "ATR trailing stop; session end",
        "risk_model": "ATR stop, VA-based reference",
        "features_required": ["prior_vah", "prior_val", "volume"],
        "lookahead_risks": ["VA computed from prior session"],
        "failure_modes": ["false breakouts on low volume; volume confirmation critical"],
        "param_grid": {"vol_mult": [1.2, 1.5], "rr_ratio": [1.5, 2.0, 2.5]},
        "notes": "Standard volume profile strategy; complements POC magnet logic.",
    },
    {
        "key": "vpoc_shift_momentum",
        "family": "Q_VOL_PROFILE",
        "name": "VPOC Shift Momentum",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["15min"],
        "data_required": ["ohlcv"],
        "hypothesis": "When the intraday Volume POC shifts directionally, institutions are repositioning; trade the VPOC shift direction",
        "entry_logic": "VPOC shifts > N price levels from prior bar's VPOC in one direction; enter in shift direction",
        "exit_logic": "VPOC stabilises (< 1 tick shift for N bars); ATR stop",
        "risk_model": "ATR stop",
        "features_required": ["intraday_vpoc"],
        "lookahead_risks": ["VPOC update uses bars closed so far in session"],
        "failure_modes": ["intraday VPOC computed in real time can jump on thin bars"],
        "param_grid": {"vpoc_shift_ticks": [3, 5], "rr_ratio": [1.5, 2.0]},
        "notes": "Dynamic VPOC computation is computationally intensive at 1-minute bars.",
    },
    # ── Family R: Time Series ──────────────────────────────────────────────────
    {
        "key": "hurst_regime_filter",
        "family": "R_TIME_SERIES",
        "name": "Hurst Exponent Regime Filter",
        "priority": 2,
        "status": "research",
        "symbols": ["GC", "SI"],
        "timeframes": ["5min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Hurst exponent > 0.5 indicates trending (persistent) series; H < 0.5 indicates mean-reverting. Filter signals based on H regime.",
        "entry_logic": "Compute rolling Hurst exponent on close; H > 0.55 → only take trend signals; H < 0.45 → only take mean-reversion signals",
        "exit_logic": "Dependent on underlying signal",
        "risk_model": "ATR stop from underlying signal",
        "features_required": ["close"],
        "lookahead_risks": ["Hurst computed from prior N bars only"],
        "failure_modes": ["Hurst estimation requires long windows (100+ bars) → significant lag"],
        "param_grid": {"hurst_window": [100, 200], "h_threshold": [0.45, 0.55]},
        "notes": "Meta-filter — applied to other signals; not standalone. Computationally expensive.",
    },
    {
        "key": "return_autocorrelation_entry",
        "family": "R_TIME_SERIES",
        "name": "Short-Term Return Autocorrelation",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["1min", "5min"],
        "data_required": ["ohlcv"],
        "hypothesis": "Intraday 1-minute returns show positive autocorrelation at lag 1-2 during trend periods; negative autocorrelation during mean-reversion periods",
        "entry_logic": "Rolling lag-1 autocorrelation of 1m returns > threshold → momentum; < -threshold → mean reversion; enter accordingly",
        "exit_logic": "ATR stop; autocorrelation regime change",
        "risk_model": "ATR stop, regime signal",
        "features_required": ["close"],
        "lookahead_risks": ["autocorrelation from prior N bars only"],
        "failure_modes": ["autocorrelation estimate noisy over 30-60 bar windows"],
        "param_grid": {"ac_window": [20, 40, 60], "ac_threshold": [0.15, 0.20], "rr_ratio": [1.5, 2.0]},
        "notes": "Statistical time-series property; requires sufficient window for stable estimate.",
    },
    {
        "key": "halflife_mean_reversion",
        "family": "R_TIME_SERIES",
        "name": "Half-Life Mean Reversion",
        "priority": 2,
        "status": "pending",
        "symbols": ["GC", "SI"],
        "timeframes": ["5min"],
        "data_required": ["ohlcv"],
        "hypothesis": "If intraday price has a measurable half-life of mean reversion (via AR(1) regression), trade that reversion with a hold_bars matching the half-life",
        "entry_logic": "Fit AR(1) to intraday price; half_life = -log(2)/log(|beta|); if half_life < 20 bars → mean-reversion mode; fade extremes",
        "exit_logic": "Exit after half_life bars; ATR stop",
        "risk_model": "ATR stop; half-life time exit",
        "features_required": ["close"],
        "lookahead_risks": ["AR(1) fit on prior session bars only"],
        "failure_modes": ["half-life estimates change daily; parameter instability"],
        "param_grid": {"fit_window_bars": [60, 120], "entry_sigma": [1.5, 2.0]},
        "notes": "Uses statistical half-life to set hold_bars dynamically — adaptive exit.",
    },
]

# ── Write to file ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    out_path = Path(__file__).parent.parent / "08_docs" / "strategy_universe_exhaustive.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(
            {
                "meta": {
                    "generated": "2026-06-03",
                    "total_entries": len(ENTRIES),
                    "families": sorted(set(e["family"] for e in ENTRIES)),
                    "statuses": sorted(set(e["status"] for e in ENTRIES)),
                    "schema_version": "1.1",
                    "description": "Exhaustive strategy universe for the Fortress quant research system. Machine-readable companion to strategy_universe_exhaustive.md",
                },
                "strategies": ENTRIES,
            },
            f,
            indent=2,
            ensure_ascii=False,
        )
    print(f"Written: {out_path}")
    print(f"Entries: {len(ENTRIES)}")
    families = {}
    for e in ENTRIES:
        families[e["family"]] = families.get(e["family"], 0) + 1
    for fam, count in sorted(families.items()):
        print(f"  {fam}: {count}")
    survivors = [e for e in ENTRIES if e["status"] == "survivor"]
    print(f"\nSurvivors: {len(survivors)}")
    for s in survivors:
        print(f"  {s['key']} ({', '.join(s['symbols'])})")
